# @package _global_

# Magpie-Align/Magpie-Air-DPO-100K-v0.1

dataset_args:
  dataset_path: ${data_dir}/shared/datasets-with-chosen-rewards/merged/magpieair-armorm
  train_split:
    name: train
    start: 0
    end: 97812  # After filtering rows on reward_tokenizer(prompt + chosen/reject) <= 2048
  eval_split:
    name: test
    end: 1992   # After filtering rows on reward_tokenizer(prompt + chosen/reject) <= 2048
    start: 0

training_args:
  eval_steps: 160
  save_steps: 160
