# @package _global_

# HuggingFaceH4/ultrafeedback_binarized

dataset_args:
  dataset_path: ${data_dir}/shared/datasets-with-chosen-rewards/merged/ultrafeedback-armorm
  train_split:
    name: train_prefs
    start: 0
    end: 61024  # After filtering rows on reward_tokenizer(prompt + chosen/reject) <= 2048
  eval_split:
    name: test_prefs
    start: 0
    end: 1995    # After filtering rows on reward_tokenizer(prompt + chosen/reject) <= 20485


training_args:
  eval_steps: 100
  save_steps: 100
